# If starting from a tensorflow image does not work, try starting from a nvidia/cuda container

FROM   nvidia/cuda:10.1-cudnn7-devel

MAINTAINER Aniket Tekawade <aniketkt@gmail.com>


RUN	apt update && \
	apt install -y python3.6 && \
	apt install libgl1-mesa-glx -y && \
	apt install python3-pip -y && \
	pip3 install --upgrade setuptools && \
	python3 -m pip install --upgrade pip && \
	python3 -m pip install --upgrade setuptools


COPY	. CTSegNet/.

RUN	pip3 install tensorflow-gpu==2.1.0 && \
	pip3 install CTSegNet/. && \
	pip3 install jupyter


